name: Jen Cotten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#330405'
    - '#8c0c13'
    - '#6e178c'
    - '#440c56'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
