name: Jen Cotten
favicon: null
layout_spectrum: 0.99676
typography_spectrum: 0.7527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f6f8'
    - '#0f1015'
    - '#aaa36d'
    - '#544f49'
    - '#f53462'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
