name: Jen Cotten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b8150'
    - '#161a1d'
    - '#e2e9f1'
    - '#4a5149'
    - '#e23738'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
