name: Jen Cotten
favicon: null
layout_spectrum: 0.24946
typography_spectrum: 0.7527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#403931'
    - '#b49a94'
    - '#808274'
    - '#9fcf51'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
