name: Jen Cotten
favicon: null
layout_spectrum: 0.99244
typography_spectrum: 0.75486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424941'
    - '#11161a'
    - '#938e8a'
    - '#d8e5f5'
    - '#9a1733'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
