name: Jen Cotten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f6f8'
    - '#101116'
    - '#827c48'
    - '#a9a26c'
    - '#544f49'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
