name: Jen Cotten
favicon: null
layout_spectrum: 0.99698
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f6f8'
    - '#c0ba7e'
    - '#3d5630'
    - '#5e7945'
    - '#ec2755'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0
purpose: []
