name: Jen Cotten
favicon: null
layout_spectrum: 0.9631236982531846
typography_spectrum: 0.0900917761027813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.44457843038253486
  lightness: 0.5580748375505209
  saturation: 0.5487094316631556
  rhythmicContrast: 0.6613357211463153
purpose: []
