name: Jen Cotten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0f11'
    - '#e2eaf6'
    - '#648671'
    - '#aec7a1'
    - '#f33263'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
